services:
  postgres:
    image: postgres:16-alpine
    container_name: staylocal-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: staylocal
      POSTGRES_PASSWORD: staylocal
      POSTGRES_DB: staylocal
    ports:
      - "5432:5432"
    volumes:
      - staylocal_pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: staylocal-mail
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI web en http://localhost:8025

volumes:
  staylocal_pgdata:
