import type { Config } from "tailwindcss";

export default {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3f2",
        "primary-fixed-dim": "#ffb68d",
        "surface": "#fcf9f8",
        "on-tertiary-fixed-variant": "#394b3d",
        "surface-variant": "#e5e2e1",
        "on-tertiary-container": "#f6fff4",
        "surface-tint": "#9a4600",
        "primary": "#974400",
        "inverse-on-surface": "#f3f0ef",
        "surface-bright": "#fcf9f8",
        "moss": "#4A5D4E",
        "on-secondary-fixed-variant": "#474744",
        "primary-container": "#bb5808",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#d3e8d5",
        "error-container": "#ffdad6",
        "secondary": "#5e5e5b",
        "on-secondary": "#ffffff",
        "ink": "#1A1A1A",
        "background": "#fcf9f8",
        "on-primary-fixed": "#321200",
        "surface-dim": "#dcd9d9",
        "tertiary-fixed-dim": "#b7ccb9",
        "on-surface": "#1c1b1b",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#763400",
        "line": "#E5E1D8",
        "on-secondary-container": "#63635f",
        "on-tertiary": "#ffffff",
        "outline": "#8a7266",
        "on-error-container": "#93000a",
        "terracotta-deep": "#A0522D",
        "outline-variant": "#ddc1b3",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c8c6c2",
        "bone": "#F9F7F2",
        "secondary-fixed": "#e4e2dd",
        "on-tertiary-fixed": "#0e1f13",
        "paper": "#FFFFFF",
        "ochre": "#DAA520",
        "line-hair": "#F5F2ED",
        "on-error": "#ffffff",
        "inverse-primary": "#ffb68d",
        "on-secondary-fixed": "#1b1c19",
        "tertiary-container": "#667969",
        "surface-container-high": "#eae7e7",
        "surface-container": "#f0eded",
        "terracotta": "#D2691E",
        "ink-mute": "#808080",
        "line-soft": "#F0EDE6",
        "on-surface-variant": "#564338",
        "secondary-container": "#e1dfdb",
        "inverse-surface": "#313030",
        "surface-container-highest": "#e5e2e1",
        "primary-fixed": "#ffdbc9",
        "on-background": "#1c1b1b",
        "tertiary": "#4d6151",
        "bone-2": "#F1EFEA",
        "on-primary-container": "#fffbff",
        "ink-soft": "#4A4A4A"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1.5rem",
        "stack-lg": "2rem",
        "stack-sm": "0.5rem",
        "margin-mobile": "1rem",
        "stack-md": "1rem",
        "container-max": "76rem",
        "container-prose": "62ch"
      },
      fontFamily: {
        "label-caps": ["Plus Jakarta Sans"],
        "headline-md": ["Literata"],
        "body-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Literata"],
        "body-md": ["Plus Jakarta Sans"],
        "mono-price": ["JetBrains Mono"],
        "display-lg": ["Literata"]
      },
      fontSize: {
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "mono-price": ["16px", { "lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      },
      boxShadow: {
        "soft": "0 4px 20px -2px rgba(26, 26, 26, 0.05)",
        "warm": "0 10px 30px -5px rgba(210, 105, 30, 0.08)"
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
} satisfies Config;
